# LightChain L1 Mainnet Genesis Configuration

# Chain information
chain_id: 1001 # Unique LightChain L1 Mainnet ID
network_id: 1001
chain_name: "LightChain L1 Mainnet"

# Genesis block configuration
genesis:
  timestamp: "2024-12-31T00:00:00Z" # Mainnet launch
  parent_hash: "0x0000000000000000000000000000000000000000000000000000000000000000"
  extra_data: "LightChain L1 - Developer-First Blockchain with HPoS"
  gas_limit: "30000000" # Higher limit for mainnet
  difficulty: "0x1"

# Consensus configuration
consensus:
  type: "hpos" # Hybrid Proof of Stake (L1 native)
  epoch_length: 100
  block_time: "2s"
  min_validators: 3
  max_validators: 21 # Optimized validator set

  # Staking parameters
  staking:
    min_stake: "1000000000000000000000" # 1000 LIGHT tokens (18 decimals)
    slash_fraction_double_sign: "0.05" # 5%
    slash_fraction_downtime: "0.01" # 1%
    downtime_jail_duration: "600s" # 10 minutes

# Initial validators (REPLACE WITH YOUR ACTUAL VALIDATORS)
validators:
- address: "0xYOUR_VALIDATOR_ADDRESS_1"
  name: "Genesis Validator 1"
  pub_key: "0xYOUR_VALIDATOR_PUBKEY_1"
  stake: "100000000000000000000000" # 100K LIGHT
  commission_rate: "0.05" # 5%

- address: "0xYOUR_VALIDATOR_ADDRESS_2"
  name: "Genesis Validator 2"  
  pub_key: "0xYOUR_VALIDATOR_PUBKEY_2"
  stake: "100000000000000000000000" # 100K LIGHT
  commission_rate: "0.05" # 5%

- address: "0xYOUR_VALIDATOR_ADDRESS_3"
  name: "Genesis Validator 3"
  pub_key: "0xYOUR_VALIDATOR_PUBKEY_3"
  stake: "100000000000000000000000" # 100K LIGHT
  commission_rate: "0.05" # 5%

# Initial token allocation (1 Billion LIGHT Total)
allocations:
# Founder allocation (200M LIGHT - 20%)
- address: "0xYOUR_WALLET_ADDRESS_HERE" # UPDATE WITH YOUR WALLET
  balance: "200000000000000000000000000" # 200M LIGHT

# Team allocation (50M LIGHT - 5%)
- address: "0x1000000000000000000000000000000000000002"
  balance: "50000000000000000000000000" # 50M LIGHT

# Ecosystem fund (100M LIGHT - 10%)
- address: "0x1000000000000000000000000000000000000003"
  balance: "100000000000000000000000000" # 100M LIGHT

# Treasury (150M LIGHT - 15%)
- address: "0x1000000000000000000000000000000000000004"
  balance: "150000000000000000000000000" # 150M LIGHT

# Validator initial stakes (300K LIGHT total)
- address: "0xYOUR_VALIDATOR_ADDRESS_1"
  balance: "100000000000000000000000" # 100K LIGHT
- address: "0xYOUR_VALIDATOR_ADDRESS_2"
  balance: "100000000000000000000000" # 100K LIGHT
- address: "0xYOUR_VALIDATOR_ADDRESS_3"
  balance: "100000000000000000000000" # 100K LIGHT

# Remaining 499.7M LIGHT (49.97%) allocated through:
# - Mining rewards (validator staking)
# - Developer incentives ($10K-$1M+ rewards)
# - Cross-chain bridge rewards
# - Community rewards

# Token configuration
token:
  name: "LightChain Token"
  symbol: "LIGHT"
  decimals: 18
  total_supply: "1000000000000000000000000000" # 1B tokens

# Gas configuration (mainnet optimized)
gas:
  min_gas_price: "1000000000" # 1 Gwei
  gas_price_oracle:
    enabled: true
    base_fee_max_change_denominator: 8
    elasticity_multiplier: 2

# Fee configuration
fees:
  transaction_fee: "21000" # Base transaction fee in gas
  contract_creation_fee: "53000" # Contract creation fee in gas
  contract_call_fee: "25000" # Contract call fee in gas

# L1 Native Features - No L2/AggLayer needed
l1_native:
  enabled: true
  finality_blocks: 3
  cross_chain_bridges: true
  native_staking: true

# Precompiled contracts
precompiles:
# Standard Ethereum precompiles
- address: "0x0000000000000000000000000000000000000001" # ecRecover
  enabled: true
- address: "0x0000000000000000000000000000000000000002" # sha256
  enabled: true
- address: "0x0000000000000000000000000000000000000003" # ripemd160
  enabled: true
- address: "0x0000000000000000000000000000000000000004" # identity
  enabled: true
- address: "0x0000000000000000000000000000000000000005" # modexp
  enabled: true
- address: "0x0000000000000000000000000000000000000006" # bn256Add
  enabled: true
- address: "0x0000000000000000000000000000000000000007" # bn256ScalarMul
  enabled: true
- address: "0x0000000000000000000000000000000000000008" # bn256Pairing
  enabled: true
- address: "0x0000000000000000000000000000000000000009" # blake2f
  enabled: true

# LightChain L1 specific precompiles
- address: "0x0000000000000000000000000000000000001001" # Cross-chain bridges
  enabled: true
- address: "0x0000000000000000000000000000000000001002" # HPoS staking operations
  enabled: true
- address: "0x0000000000000000000000000000000000001003" # Developer rewards
  enabled: true

# Smart contracts to deploy at genesis
contracts:
# Core system contracts
- name: "ValidatorSet"
  address: "0x0000000000000000000000000000000000002001"
  bytecode: "0x" # To be compiled and added

- name: "StakingManager"
  address: "0x0000000000000000000000000000000000002002"
  bytecode: "0x" # To be compiled and added

- name: "CrossChainBridge"
  address: "0x0000000000000000000000000000000000002003"
  bytecode: "0x" # To be compiled and added

- name: "DeveloperRewards"
  address: "0x0000000000000000000000000000000000002004"
  bytecode: "0x" # To be compiled and added

# Network bootstrapping (REPLACE WITH ACTUAL MAINNET NODES)
bootstrap:
  # Bootnode configurations
  bootnodes:
  - "/ip4/MAINNET_IP_1/tcp/30301/p2p/MAINNET_NODE_ID_1"
  - "/ip4/MAINNET_IP_2/tcp/30302/p2p/MAINNET_NODE_ID_2"
  - "/ip4/MAINNET_IP_3/tcp/30303/p2p/MAINNET_NODE_ID_3"

  # DNS seeds (for production)
  dns_seeds:
  - "seed1.lightchain.network"
  - "seed2.lightchain.network"
  - "seed3.lightchain.network"

# Hard fork schedule
forks:
- name: "Genesis"
  block: 0
  enabled: true

# Future upgrades can be scheduled here
- name: "DeveloperIncentivesUpgrade"
  block: 1000000
  enabled: false
  description: "Enhanced developer reward system"

- name: "CrossChainBridgesUpgrade"
  block: 2000000
  enabled: false
  description: "Universal bridge to all major chains"

# Production settings (mainnet only)
production:
  enable_dev_accounts: false
  auto_mine_blocks: false
  unlock_accounts: [] # No unlocked accounts on mainnet