# LightChain L2 Sequencer Node Configuration

# Node settings
node_type: "sequencer"
data_dir: "./data/sequencer"
log_level: "info"

# Network configuration
network:
  listen_addr: "0.0.0.0:30313"
  external_addr: ""
  bootstrap_nodes:
  - "/ip4/127.0.0.1/tcp/30301/p2p/QmBootstrapNode1"
  - "/ip4/127.0.0.1/tcp/30302/p2p/QmBootstrapNode2"
  max_peers: 100
  discovery_enabled: true
  nat_enabled: true

# Consensus configuration (sequencers participate differently)
consensus:
  type: "pos"
  block_time: "1s" # Faster block time for sequencing
  epoch_length: 100
  sequencer:
    enabled: true
    batch_size: 1000
    batch_timeout: "5s"
    l1_submission_interval: "10m"

# State management
state:
  database:
    type: "badger"
    path: "./data/sequencer/state"
    cache_size: "256MB" # Larger cache for sequencer
  pruning:
    enabled: false # Sequencers keep more data
    keep_recent: 10000
    keep_every: 100

# RPC configuration
rpc:
  enabled: true
  listen_addr: "127.0.0.1:8555"
  cors_origins: [ "*" ]
  api_modules: [ "eth", "net", "web3", "lightchain", "sequencer" ]
  max_connections: 200

# WebSocket configuration
websocket:
  enabled: true
  listen_addr: "127.0.0.1:8556"
  max_connections: 100

# Metrics and monitoring
metrics:
  enabled: true
  listen_addr: "127.0.0.1:9091"
  path: "/metrics"

# AggLayer integration (sequencers have enhanced integration)
agglayer:
  enabled: true
  rpc_url: "https://agglayer-rpc.polygon.technology"
  certificate_ttl: "30m"
  batch_size: 500
  sender:
    enabled: true
    private_key_path: "./keys/aggsender-sequencer.key"
    poll_interval: "5s"
    batch_certificates: true
  oracle:
    enabled: true
    update_interval: "15s"
    verification_depth: 3

# Sequencer-specific settings
sequencer:
  mempool:
    max_size: 50000
    max_tx_per_account: 1000
    price_limit: "1000000000" # 1 Gwei minimum
    price_bump: 10 # 10% price bump for replacement

  batching:
    max_batch_size: 1000
    max_batch_bytes: "128KB"
    batch_timeout: "5s"
    compression_enabled: true

  fee_management:
    base_fee_enabled: true
    fee_history_blocks: 100
    fee_cap_multiplier: 2

# L1 Integration (for batch submission)
l1:
  rpc_url: "https://eth-mainnet.alchemyapi.io/v2/YOUR_API_KEY"
  contract_address: "0x..." # L1 contract address
  private_key_path: "./keys/l1-submitter.key"
  gas_limit: 500000
  max_gas_price: "100000000000" # 100 Gwei

# Security settings
security:
  keystore_path: "./keys"
  password_file: "./keys/password.txt"
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Performance tuning
performance:
  max_tx_pool_size: 50000
  block_gas_limit: "30000000" # Higher gas limit for sequencer
  tx_timeout: "60s"
  sync_mode: "full"
  gc_percent: 10

# Development settings (for local testing)
development:
  enable_dev_mode: true
  auto_mine_blocks: true
  dev_period: "1s" # Sequencer creates blocks every second
  generate_empty_blocks: true
  continuous_mining: true # Never stop mining
  auto_seal_blocks: true
  background_mining: true # Mine in background continuously
