# LightChain L1 Validator Node Configuration

# Node settings
node_type: "validator"
data_dir: "./data/validator"
log_level: "info"

# Network configuration
network:
  listen_addr: "0.0.0.0:30303"
  external_addr: ""
  bootstrap_nodes:
  - "/ip4/127.0.0.1/tcp/30301/p2p/QmBootstrapNode1"
  - "/ip4/127.0.0.1/tcp/30302/p2p/QmBootstrapNode2"
  max_peers: 50
  discovery_enabled: true
  nat_enabled: true

# Consensus configuration
consensus:
  type: "hpos" # Hybrid Proof of Stake (L1 native)
  block_time: "2s"
  epoch_length: 100
  validator:
    enabled: true
    stake_amount: "1000000000000000000000" # 1000 LIGHT minimum stake
    commission_rate: "0.05" # 5% commission
    auto_compound: true
    performance_tracking: true

# State management
state:
  database:
    type: "badger" # Lightweight embedded database
    path: "./data/validator/state"
    cache_size: "128MB"
  pruning:
    enabled: true
    keep_recent: 1000
    keep_every: 100

# RPC configuration
rpc:
  enabled: true
  listen_addr: "127.0.0.1:8545"
  cors_origins: [ "*" ]
  api_modules: [ "eth", "net", "web3", "lightchain" ]
  max_connections: 100

# WebSocket configuration
websocket:
  enabled: true
  listen_addr: "127.0.0.1:8546"
  max_connections: 50

# Metrics and monitoring
metrics:
  enabled: true
  listen_addr: "127.0.0.1:9090"
  path: "/metrics"

# L1 Native Features - No L2/AggLayer integration needed
l1_native:
  enabled: true
  finality_blocks: 3 # L1 native finality
  cross_chain_bridges: true
  native_staking: true

# Security settings
security:
  keystore_path: "./keys"
  password_file: "./keys/password.txt"
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Performance tuning
performance:
  max_tx_pool_size: 10000
  block_gas_limit: "10000000"
  tx_timeout: "30s"
  sync_mode: "full"
  gc_percent: 20

# Development settings (for local testing)
development:
  enable_dev_mode: true
  auto_mine_blocks: true
  dev_period: "2s" # Create blocks every 2 seconds like real blockchain
  generate_empty_blocks: true # Create blocks even without transactions
  min_empty_block_interval: "10s" # At least one block every 10 seconds
  continuous_mining: true # Never stop mining blocks
  auto_seal_blocks: true # Automatically seal blocks
